# Generated by Django 3.2.13 on 2022-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=20)),
                ('owner', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(default=0, null=True)),
                ('rating', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('project', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('project', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(null=True)),
                ('client_call_expe', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(blank=True, max_length=20)),
                ('project_list', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(null=True)),
                ('client_call', models.IntegerField(null=True)),
            ],
        ),
    ]
