# Generated by Django 3.2.13 on 2022-05-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='APIVIEW.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
