# Generated by Django 4.1.1 on 2022-10-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0002_projectmanager_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='developer',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('NodeJs', 'NodeJs'), ('Blockchain', 'Blockchain')], default='Python', max_length=30),
        ),
        migrations.AddField(
            model_name='developer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_lead', to='APIVIEW.lead'),
        ),
        migrations.AddField(
            model_name='developer',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_project_manager', to='APIVIEW.projectmanager'),
        ),
    ]
