# Generated by Django 4.1.1 on 2022-10-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0004_remove_developer_developer_remove_developer_lead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developers',
        ),
    ]
