# Generated by Django 4.1.1 on 2022-10-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0005_delete_developers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('project', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(null=True)),
                ('developer', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('NodeJs', 'NodeJs'), ('Blockchain', 'Blockchain')], default='Python', max_length=30)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_lead', to='APIVIEW.lead')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_project_manager', to='APIVIEW.projectmanager')),
            ],
        ),
    ]
