# Generated by Django 4.1.1 on 2022-10-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0008_alter_developers_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIVIEW.lead'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIVIEW.projectmanager'),
        ),
    ]
